services:
  drupal:
    image: drupal:10
    ports:
      - "8800:80"
    volumes:
      - drupal-data:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db-data:/var/lib/mysql
    ports:
      # host port : container port
      - "3386:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8801:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    depends_on:
      - db

volumes:
  drupal-data:
  db-data:
