services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile.drupal
    container_name: drupal
    environment:
      DRUPAL_DB_HOST: mariadb
      DRUPAL_DB_PORT: 3306
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal_password
    volumes:
      - drupal_data:/var/www/html
    ports:
      - "8081:80"
    networks:
      - internal
      - local_network
