services:
  mariadb:
    extends:
      file: mariadb.yml
      service: mariadb

  phpmyadmin:
    extends:
      file: phpmyadmin.yml
      service: phpmyadmin

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
  local_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

volumes:
  db_data:
