import csv

saints_by_country = {


"American" : [
"Frances Xavier Cabrini",
"Damien of Molokai",
"Katharine Drexel",
"Rose Philippine Duchesne",
"Mother Theodore Guerin",
"John Neumann",
"Elizabeth Ann Seton",
],
"Armenian" : [
"Euthymius the Great",
"Gregory Narekatzi",
"Gregory the Illuminator",
"Isaac the Great",
"Mesrop Mashtots",
"Vardan Mamikonian",
"Nerses I the Great",
],
"Australian" : [
"Mary MacKillop",
],
"Austrian" : [
"John of Capistrano",
],
"Belgian" : [
"Damien of Molokai",
],
"Bohemian" : [
"Adalbert",
"John of Nepomuk",
"Ludmila",
"John Neumann",
"Wenceslas I",
],
"Bulgarian" : [
"Boris I",
"Cyprian",
"Euthymius of Turnovo",
"Peter I",
],
"Byzantine" : [
"John III Ducas Vatatzes",
"Theophanes the Confessor",
],
"Canadian" : [
"Jean de Brebeuf",
"Isaac Jogues",
],
"Danish" : [
"Canute IV",
],
"Dutch" : [
"Peter Canisius",
],
"Egyptian" : [
"Anastasius Sinaita (birthplace unconfirmed)",
"Anthony of Egypt",
"Athanasius",
"Catherine of Alexandria",
"Clement of Alexandria",
"Cyril of Alexandria",
"Dionysius of Alexandria",
"Dioscorus",
"Macarius the Egyptian",
"Pachomius",
"Paul of Thebes",
"Sarapion",
"Shenute",
"Theophilus of Alexandria",
],
"English" : [
"Aelfheah",
"Aelred of Rievaulx",
"Aidan",
"Alban",
"Anselm of Canterbury",
"Augustine of Canterbury",
"Thomas Becket",
"Bede the Venerable",
"Benedict Biscop",
"Boniface",
"Edmund Campion",
"Thomas de Cantelupe",
"Chad",
"Margaret Clitherow",
"Cuthbert",
"Dunstan of Canterbury",
"Edmund of Abington",
"Edward the Confessor",
"Hilda of Whitby",
"Hugh of Lincoln",
"Gilbert of Sempringham",
"John of Beverley",
"Justus",
"Laurentius of Canterbury",
"Cuthbert Mayne",
"Mellitus of Canterbury",
"Thomas More",
"Osmund of Salisbury",
"Oswald of Northumbria",
"Oswald of York",
"Patrick",
"Paulinus",
"Richard of Chichester",
"Stephen Harding",
"Swithin",
"Theodore of Canterbury",
"Wilfrid",
"Willibrord",
"Wulfstan",
],
"Frankish" : [
"Ansgar",
"Clotilda",
"Cunibert",
"Dagobert I",
"Radegunda",
],
"French" : [
"Adelaide",
"Agobard",
"Madeleine-Sophie Barat",
"Benezet",
"Bernadette of Lourdes",
"Bernard de Clairvaux",
"Jean de Brebeuf",
"Jane Frances de Chantal",
"Colette",
"Denis",
"Rose Philippine Duchesne",
"John Eudes",
"Faustus of Riez",
"Felix of Valois",
"Vincent Ferrer",
"Francis of Sales",
"Fulbert of Chartres",
"Genevieve",
"Germanus of Paris",
"Mother Theodore Guerin",
"Hilary of Poitiers",
"Hugh of Cluny",
"Hugh of Lincoln",
"Ivo of Chartres",
"Joan of Arc",
"John of Matha",
"Isaac Jogues",
"Claude La Colombiere",
"Jean-Baptiste de La Salle",
"Louis IX",
"Louise de Marillac",
"Martin of Tours",
"Mary of the Incarnation",
"Louis-Marie Grignion de Montfort",
"Odo of Cluny",
"Paschasius Radbertus",
"Peter Nolasco",
"Peter the Venerable",
"Remigius of Reims",
"Therese of Lisieux",
"Jean-Baptiste-Marie Vianney",
"Vincent of Lerins",
],
"Gaulish" : [
"Ambrose",
"Caesarius of Arles",
"Germanus of Auxerre",
"Germanus of Paris",
"Gregory of Tours",
"Hilary of Arles",
"Paulinus of Nola",
],
"German" : [
"Albertus Magnus",
"Anno",
"Ansgar",
"Benno",
"Bruno of Querfurt (Saxon)",
"Bruno the Carthusian",
"Bruno the Great",
"Gotthard",
"Henry II",
"Hildegard",
"Clement Mary Hofbauer",
"Norbert of Xanten",
"Edith Stein",
"Heinrich Suso",
"Ulrich",
],
"Greek" : [
"Anterus",
"Clement of Alexandria",
],
"Saints Cyril and Methodius" : [
"Diadochus of Photice (birthplace unconfirmed)",
"Dioynsius (birthplace unconfirmed)",
"Eleutherius",
"Markos Eugenikos",
"Eusebius",
"Eustathius of Thessalonica",
"Hegesippus",
"Hyginus",
"Maximus the Greek",
"Nicodemus the Hagiorite",
"Nilus of Ancyra",
"Gregory Palamas",
"Philotheus Kokkinos",
"Polycarp",
"Sixtus II",
"Telesphorus",
"Theophylactus of Ochrida",
"Zosimus",
],
"Hungarian" : [
"Elizabeth of Hungary",
"Gerard",
"Ladislas I",
"Stephen I",
],
"Indian" : [
"Mother Teresa (born in Macedonia, Ottoman Empire [now in Republic of Macedonia])",
],
"Irish" : [
"Adamnan",
"Aidan",
"Brendan",
"Brigit of Ireland",
"Ciaran of Clonmacnoise",
"Colman of Lindisfarne",
"Columba",
"Columban",
"Fridolin of Sackingen",
"Fursey",
"Gall",
"Kenneth",
"Kevin",
"Kilian",
"Malachy",
"Oengus",
"Patrick",
"Oliver Plunket",
],
"Italian" : [
"Adrian III",
"Agapetus I",
"Agatha",
"Agatho",
"Alexander I",
"Antoninus",
"Thomas Aquinas",
"Robert Bellarmine",
"Benedict II",
"Benedict of Nursia",
"Bernard of Menthon",
"Bernardine of Siena",
"Bonaventure",
"Boniface I",
"Boniface IV",
"Charles Borromeo",
"John Bosco",
"Frances Xavier Cabrini",
"Cajetan of Thiene",
"Camillus of Lellis",
"Catherine of Bologna",
"Catherine of Genoa",
"Catherine of Siena",
"Catherine",
"Celestine V",
"Peter Chrysologus",
"Clare of Assisi",
"Giuseppe Cottolengo",
"Damasus I",
"Peter Damian",
"Deusdedit",
"Eugenius I",
"Eusebius of Vercelli",
"Felix III",
"Felix IV",
"Frances of Rome",
"Francis of Assisi",
"Francis of Paola",
"Gelasius I",
"Gerard",
"Aloysius Gonzaga",
"Gregory I",
"Gregory II",
"Gregory VII",
"Hilary",
"Hormisdas",
"Innocent I",
"Jacobus de Voragine",
"John I",
"John XXIII",
"Justus",
"Lawrence of Brindisi",
"Leo I",
"Leo II",
"Leo III",
"Leo IV",
"John Leonardi",
"Alfonso Maria de Liguori",
"Lucy",
"Martin I",
"Angela Merici",
"Methodius I",
"Philip Neri",
"Nicholas I",
"Nilus of Rossano",
"Padre Pio",
"Paschal I",
"Paul I",
"Paul of the Cross",
"Peter Martyr",
"Pius V",
"Pius X",
"Romuald of Ravenna",
"Sergius I",
"Silverius",
"Siricius",
"Symmachus",
"Vitalian",
"Antonio Maria Zaccaria",
"Zacharias",
"Zephyrinus (birthplace unconfirmed)",
],
"Korean" : [
"Kim Dae-gon",
],
"Mexican" : [
"Juan Diego",
],
"Mohawk" : [
"Kateri Tekakwitha",
],
"Norwegian" : [
"Olaf II Haraldsson",
],
"Numidian" : [
"Augustine",
],
"Palestinian" : [
"Epiphanius of Constantia",
"Hilarion",
"Justin Martyr",
"Sabas",
"Theodosius of Palestine",
],
"Peruvian" : [
"Martin de Porres",
"Rose of Lima",
],
"Polish" : [
"Jadwiga",
"John Paul II",
"Maksymilian Maria Kolbe",
"Stanislaus of Krakow",
],
"Portuguese" : [
"Anthony of Padua",
"Elizabeth of Portugal",
"Nuno Alvares Pereira",
],
"Roman" : [
"Agnes",
"Anacletus",
"Anastasius I",
"Arsenius the Great",
"Calixtus I",
"John Cassian",
"Cecilia",
"Celestine I",
"Christopher",
"Clement I",
"Constantine I",
"Cornelius",
"Crispin",
"Crispinian",
"Cyril of Jerusalem",
"Erasmus",
"Eustace",
"Eutychian",
"Fabian",
"Felix I",
"Gaius",
"George",
"Helena",
"Hesychius of Jerusalem",
"Hippolytus of Rome",
"Januarius",
"Jerome",
"Julius I",
"Juvenal (birthplace unconfirmed)",
"Lawrence",
"Liberius",
"Linus",
"Lucius I",
"Marcellinus",
"Marcellus I",
"Mark",
"Miltiades",
"Perpetua",
"Pontian",
"Quadratus",
"Sebastian",
],
"Saints Sergius and Bacchus" : [
"Simplicius",
"Siricius",
"Sixtus I",
"Sixtus II",
"Sixtus III",
"Soter",
"Stephen I",
"Sylvester I",
"Urban I",
"Valentine",
"Victor I",
],
"Russian" : [
"Alexis",
"Joseph of Volokolamsk",
"Nikolay Kasatkin",
"Alexander Nevsky",
"Olga",
"Seraphim of Sarov",
"Sergius of Radonezh",
"Nil Sorsky",
"Stephen of Perm",
"Tikhon",
"Innocent Veniaminov",
],
"Salvadoran" : [
"Oscar Romero",
],
"Scottish" : [
"Kentigern",
"Margaret of Scotland",
"Ninian",
],
"Serbian" : [
"Sava",
],
"Spanish" : [
"Agobard",
"Francis Borgia",
"Joseph Calasanz",
"Peter Claver",
"Dominic",
"Josemaria Escriva de Balaguer",
"Ignatius of Loyola",
"Isidore of Sevilla",
"John of Avila",
"John of the Cross",
"Peter of Alcntara",
"Raymond of Penafort",
"Junipero Serra",
"Teresa of Avila",
"Francis Xavier",
],
"Sudan" : [
"Josephine Bakhita",
],
"Swedish" : [
"Bridget of Sweden",
"Catherine of Sweden",
],
"Swiss" : [
"Maurice",
"Nicholas of Flue",
],
"Syrian" : [
"Andrew of Crete",
"John Chrysostom",
"John Climacus (birthplace unconfirmed)",
"Ephraem Syrus",
"Eusebius of Samosata",
"Evaristus",
"Gregory III",
"John of Damascus",
"Lucian of Antioch",
"Margaret of Antioch",
"John Moschus",
"Simeon Stylites",
"Theophilus of Antioch",
"Pelagia of Antioch",
],
"Tunisian" : [
"Cyprian",
"Fulgentius of Ruspe",
],
"Turkish" : [
"Athanasius I",
"Athanasius the Athonite",
"Basil the Great",
"Blaise",
"Cosmas",
"Damian",
"Eustathius of Antioch",
"Eustathius of Thessalonica",
"Flavian",
"Gennadius I of Constantinople",
"Germanus I",
"Gregory of Nazianzus",
"Gregory of Nyssa",
"Gregory Thaumaturgus",
"Irenaeus (birthplace unconfirmed)",
"John the Faster",
"Maximus the Confessor",
"Meletius of Antioch",
"Methodius I",
"Nicephorus I",
"Nicholas",
"Nicholas I",
"Gregory Palamas",
"Photius",
"Severus of Antioch",
"Symeon the New Theologian",
"Theodore Studites",
],
"Ugandan" : [
"Pontian Ngondwe",
],
"Ukrainian" : [
"Anthony of Kiev",
"Vladimir I",
],
"Visigothic" : [
"Hermenegild",
],
"Welsh" : [
"David",
],
"archangels" : [
"Gabriel",
"Michael",
"Raphael",
],

"biblical" : [
"Andrew",
"Anne",
"Barnabas",
"Bartholomew",
"James, son of Alphaeus",
"James, son of Zebedee",
"James, the Lord's brother",
"Joachim",
"John the Apostle",
"John the Baptist",
"Joseph",
"Joseph of Arimathea",
"Judas",
"Luke",
"Mark",
"Mary",
"Mary Magdalene",
"Matthew",
"Matthias",
"Paul",
"Peter",
"Philip the Apostle",
"Philip the Evangelist",
"Silas",
"Simon the Apostle",
"Stephen",
"Thomas",
"Timothy",
"Titus",
"Veronica",
],
"other" : [
"Barbara",
"Ursula",
]
}

def save_to_csv(data, filename):

    with open(filename, mode='w', newline='') as file:
        writer = csv.writer(file, quoting=csv.QUOTE_ALL, quotechar='"')
        writer.writerows(data)


saints = [['saint_name', 'origin']]
for country,saints_list in saints_by_country.items():
    print(country)
    for saint_name in saints_list:
        saints.append([saint_name, country])

save_to_csv(saints, 'saints_by_country.csv')